config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'upload' => 'images#new', :as => 'upload'
  get 'images/index'
  get 'images/new'
  get 'images/create'
  get 'images/destroy'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/create'
  get 'categories/update'

  resources :images, :categories

  root 'images#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# this is a ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# this is a model category
class Category < ApplicationRecord
  has_many :images
end

app/models/image.rb
# frozen_string_literal: true

# this is a model image
class Image < ApplicationRecord
  belongs_to :category

  mount_uploader :image , ImageUploader

  before_save :update_image_attributes

private

  def update_image_attributes
    if image.present? && image_changed?
      self.image_content_type = image.file.content_type
      self.image_file_size = image.file.size
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# this is a ApplicationController
class ApplicationController < ActionController::Base
  before_action :getcategoryNav

  protect_from_forgery with: :exception

  private
  def getcategoryNav
    @categoryNav = Category.all
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# this is a CategoriesController
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"

      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category Updated'

      redirect_to category_path(params[:id])
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

# this is a ImagesController
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @categories = Category.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = 'Image Created'

      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    flash[:notice]='image deleted'

    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :category_id, :image_title,
      :image_descrip, :image_file_size, :image_content_type, :remote_image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/edit.html.erb
<h2> Edit Category</h2>
<%= form_for  @category do |f|%>
  <!-- check for errors -->
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
        <!--Show errors -->
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class:'form-control'%><br />
    </div>
    <%= f.submit "Submit", class: 'btn btn-primary'%>
    <%=link_to "Cancel", categories_path, class:'btn btn-default'%>
<% end %>

<h3 class="page-header">Images in<%= @category.name %></h3>
<div id="edit_images">
  <% if @images.exists? %>
    <% @images.each_slice(6) do |image| %>
      <div class="row">
        <% image.each do |image| %>
          <div class="col-md-2">
            <%= image_tag image.image_url(:thumb) %>
            <center><%= link_to "Delete", image_path(image), class:'delete', method: :delete, data: {confirm: 'Are you sure?'}%></center>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>

app/views/categories/new.html.erb
<h2> Add New Category</h2>
<%= form_for  @category do |f|%>
  <!-- check for errors -->
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
        <!--Show errors -->
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class:'form-control'%><br />
    </div>
    <%= f.submit "Submit", class: 'btn btn-primary'%>
    <%=link_to "Cancel", categories_path, class:'btn btn-default'%>
<% end %>

app/views/categories/show.html.erb
<div id="gallery">
<h2><% @category.name %><small class="pull-right"><%= link_to "Edit",
   edit_category_path %></small></h2>
<% if @images.exists? %>
  <% @images.each_slice(4) do |image| %>
    <div class= "row">
      <% image.each do |image| %>
        <div class="grid_4">
          <div class="gall_block">
            <div class="maxheight">
              <a href="<%= image.image_url() %>" class="gall_item" data-title= "<%= image.image_title %>"></a>
              <div class="gall_bot">
              <div class="text1"> <%= image.image_title %> </div>
              <div class="line"></div>
              <div class="desc"><%= image.image_descrip %> <div>
              <br>
              </a>
              <a href="#" class="btn"><%= image_tag image.image_url(:thumb) %></a></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p> there are no images. </p>
<% end %>

app/views/images/index.html.erb
<% if @images.exists? %>
  <% @images.each_slice(4) do |image| %>
    <div class= "row">
      <% image.each do |image| %>
        <div class="grid_4">
          <div class="gall_block">
            <div class="maxheight">
              <a href="<%= image.image_url() %>" class="gall_item" data-title= "<%= image.image_title %>"></a>
              <div class="gall_bot">
              <div class="text1"> <%= image.image_title %> </div>
              <div class="line"></div>
              <div class="desc"><%= image.image_descrip %> <div>
              <br>
              </a>
              <a href="#" class="btn"><%= image_tag image.image_url(:thumb) %></a></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p> there are no images. </p>
<% end %>

app/views/images/new.html.erb
<h2>Upload Image</h2>

<%= form_for @image, :html => { :multipart => true } do |f| %>
   <!--check for errors-->
    <% if @image.errors.any? %>
      <% @image.errors.full_messages.each do |msg| %>
      <!--Show errors -->
        <div class= "alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

	<div class = "from-group">
	  <%= f.label :image_title %>
	  <%= f.text_field :image_title ,class: 'form-control'%>
	</div>

	<div class = "from-group">
	  <%= f.label :category %>
      <%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]},
       {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>

	<div class = "from-group">
	  <%= f.label :image_descrip %>
	  <%= f.text_area :image_descrip, class: 'form-control' %>
	</div>

    <div class="form-control">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", images_path, class:'btn btn-default' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--==============================
              header
=================================-->
<header>
<!--==============================
            Stuck menu
=================================-->
  <section id="stuck_container">
    <div class="container">
      <div class="row">
        <div class="grid_12">

            <nav>
              <ul class="sf-menu">
               <li ><% link_to "Home", root_path %></li>
               <% @categoryNav.each do |category|%>
                 <li><%= link_to category.name, category_path(category.id)%></li>
               <% end %>
             </ul>
            </nav>

          <div class="navigation ">
            <nav>
              <ul class="sf-menu">
               <li> <%= link_to "Upload Photo", upload_path %></li>
               <li> <%= link_to "Add Category", new_category_path %></li>
             </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </section>
</header>

<!--=====================
          Content
======================-->
<section class="content gallery pad1"><div class="ic">More Website
Templates @ TemplateMonster.com - July 30, 2018!</div>
  <div class="container">
    <!--Alerts & Messages-->
      <% if flash[:notice]%>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert]%>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    <%= yield %>
  </div>
</section>
<!--==============================
              footer
=================================-->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="grid_12">
        <div class="socials">
          <a href="#" class="fa fa-twitter"></a>
          <a href="#" class="fa fa-facebook"></a>
          <a href="#" class="fa fa-google-plus"></a>
          <a href="#" class="fa fa-pinterest"></a>
        </div>
        <div class="copyright"><span class="brand">Bliss </span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a> <div>Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a></div>
        </div>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>